spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: "jdbc:mariadb://ca.martian.tk:60330/gpt_dev?sslMode=VERIFY_CA&serverTimezone=GMT-4&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull"
    username: gpt_dev
    password: SCygJ4uWK48jNtGf

  redis:
    host: ca.martian.tk
    password: 3DSyexKXX6uGG89S
    ssl: true
    database: 1

upload:
  recharge:
    path: /tmp

python:
    url:
     root: "/Users/juzi/Project/Shawn/spider/"
