spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/gpt_schema?serverTimezone=GMT-4&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull"
    username: root
    password: Aa111111

  redis:
    host: 173.82.205.214
    password: 3DSyexKXX6uGG89S
    database: 1
