###
GET https://api.openai.com/v1/models
Authorization: Bearer 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

### createCompletion-openai
POST https://api.openai.com/v1/completions
Authorization: Bearer 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
Content-Type: application/json

{
  "model": "ada",
  "prompt": "Somebody once told me the world is gonna roll me",
  "echo": true,
  "user": "testing",
  "n": 3
}

### streamCompletion-openai
POST https://api.openai.com/v1/completions
Authorization: Bearer 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
Content-Type: application/json

{
  "model": "ada",
  "prompt": "Somebody once told me the world is gonna roll me",
  "echo": true,
  "user": "testing",
  "n": 3,
  "stream": true
}

###
POST https://api.openai.com/v1/images/generations
Authorization: Bearer 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
Content-Type: application/json

{
  "prompt": "A cow breakdancing with a turtle"
}

### createChatCompletion-openai
POST https://api.openai.com/v1/chat/completions
Authorization: Bearer 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
Content-Type: application/json

{
  "model": "gpt-3.5-turbo",
  "messages": [
    {
      "role": "user",
      "content": "You are a dog and will speak as such."
    }
  ],
  "n": 1,
  "max_tokens": 50,
  "logit_bias": {}
}

### streamChatCompletion-openai
POST https://api.openai.com/v1/chat/completions
Authorization: Bearer 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
Content-Type: application/json

{
  "model": "gpt-3.5-turbo",
  "messages": [
    {
      "role": "system",
      "content": "You are a dog and will speak as such."
    }
  ],
  "n": 1,
  "stream": true,
  "max_tokens": 50,
  "logit_bias": {}
}

###
GET https://api.openai.com/v1/files
Authorization: Bearer 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

###
POST https://api.openai.com/v1/files
Authorization: Bearer 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
Content-Type: multipart/form-data; boundary=WebAppBoundary20230503

--WebAppBoundary20230503
Content-Disposition: form-data; name="purpose"
Content-Type: application/octet-stream # this field can be omited, open ai doesn't care the Content-Type

fine-tune
--WebAppBoundary20230503
Content-Disposition: form-data; name="file"; filename="file.json"
Content-Type: application/octet-stream # this field can be omited, open ai doesn't care the Content-Type

#< ./mvnw
{"prompt": "<prompt text>", "completion": "<ideal generated text>"}
--WebAppBoundary20230503--

###
GET https://api.openai.com/v1/files/file-cxinO0I88iHILwsrAdMAGkkp/content
Authorization: Bearer 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




###
GET http://localhost:8080/v1/models

### createCompletion-dev
POST http://localhost:8080/v1/completions
Content-Type: application/json

{
  "model": "ada",
  "prompt": "Somebody once told me the world is gonna roll me",
  "echo": true,
  "user": "testing",
  "n": 3
}

### streamCompletion-dev
POST http://localhost:8080/v1/completions
Content-Type: application/json

{
  "model": "ada",
  "prompt": "Somebody once told me the world is gonna roll me",
  "echo": true,
  "user": "testing",
  "n": 3,
  "stream": true
}

###
POST http://localhost:8080/v1/images/generations
Content-Type: application/json

{
  "prompt": "A cow breakdancing with a turtle"
}

### createChatCompletion-dev
POST http://localhost:8080/v1/chat/completions
Content-Type: application/json

{
  "model": "gpt-3.5-turbo",
  "messages": [
    {
      "role": "system",
      "content": "You are a dog and will speak as such."
    }
  ],
  "n": 1,
  "max_tokens": 50,
  "logit_bias": {}
}

### streamChatCompletion-dev
POST http://localhost:8080/v1/chat/completions
Content-Type: application/json

{
  "model": "gpt-3.5-turbo",
  "messages": [
    {
      "role": "system",
      "content": "You are a dog and will speak as such."
    }
  ],
  "n": 1,
  "stream": true,
  "max_tokens": 50,
  "logit_bias": {}
}

###
GET http://localhost:8080/v1/files

###
POST http://localhost:8080/v1/files
Content-Type: multipart/form-data; boundary=WebAppBoundary20230503

--WebAppBoundary20230503
Content-Disposition: form-data; name="purpose"
Content-Type: application/octet-stream # this field must be specified, the default value generated by idea is "*/*; charset=UTF-8", which is compatible with "application/x-www-form-urlencoded", and leads to 415 Unsupported Media Type

fine-tune
--WebAppBoundary20230503
Content-Disposition: form-data; name="file"; filename="file.json"
Content-Type: application/octet-stream # this field must be specified, the default value generated by idea is "*/*; charset=UTF-8", which is compatible with "application/x-www-form-urlencoded", and leads to 415 Unsupported Media Type

#< ./mvnw
{"prompt": "<prompt text>", "completion": "<ideal generated text>"}
--WebAppBoundary20230503--

###
GET http://localhost:8080/v1/files/file-cxinO0I88iHILwsrAdMAGkkp

###
DELETE http://localhost:8080/v1/files/file-cxinO0I88iHILwsrAdMAGkkp

###
GET http://localhost:8080/v1/fine-tunes



### createChatCompletion-openai
POST https://api.openai.com/v1/chat/completions
Authorization: Bearer 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
Content-Type: application/json

{
  "model": "gpt-3.5-turbo",
  "messages": [
    {
      "role": "user",
      "content": "请以刘德华为关键词，写一篇600到1200个字左右的汉语文章,文章中不得出现政治、色情、赌博和暴力等内容"
    }
  ],
  "temperature": 0.7
}

### createChatCompletion-dev
POST http://localhost:8080/v1/chat/completions
Content-Type: application/json

{
  "model": "gpt-3.5-turbo",
  "messages": [
    {
      "role": "user",
      "content": "请以刘德华为关键词，写一篇600到1200个字左右的汉语文章,文章中不得出现政治、色情、赌博和暴力等内容"
    }
  ],
  "stream": true,
  "temperature": 0.7
}

### createChatCompletion-prd
POST https://ai.martian.tk/v1/chat/completions
Content-Type: application/json

{
  "model": "gpt-3.5-turbo",
  "messages": [
    {
      "role": "user",
      "content": "请以刘德华为关键词，写一篇600到1200个字左右的汉语文章,文章中不得出现政治、色情、赌博和暴力等内容"
    }
  ],
  "temperature": 0.7
}

#######################################
### The following are bad requests. ###
#######################################

#@name incorrect Content-Type - openai
POST https://api.openai.com/v1/files
Authorization: Bearer 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
Content-Type: application/x-www-form-urlencoded

purpose=fine-tune&file=%7B%22prompt%22%3A%20%22%3Cprompt%20text%3E%22%2C%20%22completion%22%3A%20%22%3Cideal%20generated%20text%3E%22%7D

### too short-openai
POST https://api.openai.com/v1/chat/completions
Authorization: Bearer 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
Content-Type: application/json

{
  "model": "gpt-3.5-turbo",
  "n": 1,
  "messages": [],
  "stream": true,
  "max_tokens": 50,
  "logit_bias": {}
}

### incorrect Content-Type - dev
POST http://localhost:8080/v1/files
Content-Type: application/x-www-form-urlencoded

purpose=fine-tune&file=%7B%22prompt%22%3A%20%22%3Cprompt%20text%3E%22%2C%20%22completion%22%3A%20%22%3Cideal%20generated%20text%3E%22%7D

### too short-dev
POST http://localhost:8080/v1/chat/completions
Content-Type: application/json

{
  "model": "gpt-3.5-turbo",
  "n": 1,
  "messages": [],
  "stream": true,
  "max_tokens": 50,
  "logit_bias": {}
}
